### ISSUE TITLE
Unsafe audit

### ISSUE THREAD

**Issue by matklad** [matklad/once_cell#1]
This crate uses `unsafe` quite a bit for both `sync` and `unsync` variants of `OnceCell`. I feel rather confident about `unsync` usages of unsafe: the implementation is the same as in the `lazycell`. However the `sync` version, which is inspired by `lazy_static`, has quite a bit more of my own invention.

It would be cool if knowledgeable people in the area reviewed the code for safety issues!

**Comment by matklad** [comment]
@kohensu I initially thought just like that, but now I am thinking that SlipperyFrob is, in fact, 100% correct. Here's a manually forced reordering which I think would be correct under `Relaxed`, and which actually makes the test fail:

https://github.com/matklad/once_cell/blob/0c7c8e7194e312d0d45664f340bb9da57b0e3094/src/lib.rs#L504-L513

The problem is, the thread that calls get does not call `set_inner`, so the `call_once` synchronization has no effect on it.

**Comment by kohensu** [comment]
@matklad, my bad, I was focusing on the `get_or_init()` part.
Indeed there was a race between the `get()` and the `set()`.
By the way thank you for taking the time to correct me.

**Comment by matklad** [comment]
I've significantly reworked sync version internals. Now, for parking lot case it leverages `Once::state` method for synchronization. For std version, we have to maintain `is_initialized` flag ourselves unfortunately.

**Comment by matklad** [comment]
I think this isn't actionable at this point: we are already deployed throughout the ecosystem :)

And, well, we now have some extensive miri tests, which inspire at least some confidence!
