### ISSUE TITLE
Lazy force_mut?

### ISSUE THREAD

**Issue by camsteffen** [matklad/once_cell#113]
I see that `DerefMut` was added to `Lazy`. Should there also be `force_mut` then?

**Comment by matklad** [comment]
Yeah, we probably should add this here and to the std

**Comment by danielSanchezQ** [comment]
What is the state of this? I just realised I would need a `get_mut_or_init`. To get a `&mut` after initialisation.

**Comment by matklad** [comment]
waiting for someone to submit a PR with implementaiton, docs & tests :)

**Comment by danielSanchezQ** [comment]
> waiting for someone to submit a PR with implementaiton, docs & tests :)

Count me in then! Would need some guidance probably. But expect a PR soon 😄

**Comment by matklad** [comment]
This exists now
