### ISSUE TITLE
MaybeUninit fixme can't be fixed

### ISSUE THREAD

**Issue by WaffleLapkin** [matklad/once_cell#115]
I've found this fixme: https://github.com/matklad/once_cell/blob/af70a46a856d1ff14b9d74cb5a4b14e448a902b7/src/imp_std.rs#L21-L24 

And wanted to make a PR, but apparently, this is a breaking change — see https://github.com/matklad/once_cell/commit/d5295146e2fa80f4e7ad455fd97d21e3002ec885.

The question is — do we want to dump major version, or do we want to simply give up and remove this fixme?

**Comment by matklad** [comment]
I think we should remove fixme
