### ISSUE TITLE
How can I reset the contents

### ISSUE THREAD

**Issue by avnerbarr** [matklad/once_cell#127]
I have a function for creating the instance and initialising the cell, but in some cases, for instance under testing , i need to reset the cell to a new value.

Here is an example:

```
struct Configuration {
  // many more fields but omitted. This object gets created in the "get()" method which loads the cell
  name : String
  count : i32
}

static INSTANCE: OnceCell<Configuration> = OnceCell::new();

impl Configuration {
  pub fn get() -> &'static Configuration {
    Instance.get_or_init(|| {
      Configuration {
                    name: "blah".to_string(),
                    count: 0
      }
    })

  pub fn reset(config: Configuration) {
// how do I reset it? seems this fails if the cell had already been initialized
/// Sets the contents of this cell to `value`.
        ///
        /// Returns `Ok(())` if the cell was empty and `Err(value)` if it was
        /// full.
      INSTANCE.set(config);
  }
}
```

**Comment by matklad** [comment]
You need &mut access for that, it is impossible to reset once cell using
only a shared ref

**Comment by avnerbarr** [comment]
so what would I need to do for that to work?

**Comment by matklad** [comment]
I'd change the design to not rely on global static instance of `Config`. Otherwise, something like `OnceCell<Mutex<Config>>` or `OnceCell<ArcSwap<Config>>` should work. 

https://docs.rs/arc-swap/0.4.7/arc_swap/

**Comment by EdmundsEcho** [comment]
At some level I can see how the request here is a contradiction to the design of `once_cell`.  However, it is a feature that would be great to have: reloading the config.  Perhaps there is a version of the `once_cell` that might have the extra accounting of shared refs required to do so.  Likely a related idea, the feature would require encapsulating the shared use of the configuration in the memory that is being "reinitialized".

**Comment by matklad** [comment]
@EdmundsEcho for “ // set or get the handle to arc” bit, you can use https://docs.rs/once_cell/latest/once_cell/sync/struct.OnceCell.html#method.get_or_init

**Comment by EdmundsEcho** [comment]
@matklad -- Thank you for that suggestion; I'll update it accordingly.  FYI, the over-all solution was worth the extra effort.  Being able to reload axum (in my case) to read the config files by hitting a reload endpoint greatly improves my workflow.  Thank you!  - E

**Comment by odyslam** [comment]
Thanks, @EdmundsEcho, I have the exact use-case, and your solution seems to be working fine. Much appreciated!
