### ISSUE TITLE
What's the difference between unsync::OnceCell::from and sync::OnceCell::from

### ISSUE THREAD

**Issue by zserik** [matklad/once_cell#132]
Why is the unsync version initialized directly, but the sync version isn't?

unsync:
```rust
impl<T> From<T> for OnceCell<T> {
    fn from(value: T) -> Self {
        OnceCell { inner: UnsafeCell::new(Some(value)) }
    }
}
```

sync:
```rust
impl<T> From<T> for OnceCell<T> {
    fn from(value: T) -> Self {
        let cell = Self::new();
        cell.get_or_init(|| value);
        cell
    }
}
```

**Comment by matklad** [comment]
this is to save code: there are two `sync` impls

**Comment by zserik** [comment]
Couldn't appropriate `From` impls be added to the two `sync` impls? They would probably invoke far lesser code than currently (esp. as the code uses atomics and mutexes, which both interactions aren't required in that code path as there is only one owner which can access it).

**Comment by matklad** [comment]
Yeah, makes sense to do this.
