### ISSUE TITLE
AlmostOnceCell

### ISSUE THREAD

**Issue by tkaitchuck** [matklad/once_cell#133]
As an alternative to https://github.com/matklad/once_cell/issues/61 or https://github.com/matklad/once_cell/issues/53
in the case of a no_std environment where lazy initialization is needed, it would be useful to have an implementation which did not block (and hence depend on locking) or spin, but simply re-ran the initialization logic.

So if the initialization has been completed the existing result is used. However if init is attempted from multiple threads concurrently, then it just gets run more than once. For cases where the init is deterministic this provides a clean, zero-dependency, solution.

**Comment by matklad** [comment]
your wish is granted https://docs.rs/once_cell/1.5.2/once_cell/race/index.html

**Comment by tkaitchuck** [comment]
😀

**Comment by matklad** [comment]
BTW, could you do an API review for the race module? It currently is behind
unstable flag; if API looks good to you, I’ll stabilize it

**Comment by tkaitchuck** [comment]
Well it does look inconsistent with the others. I don't know if there is a reason for that.
[Unsync](https://docs.rs/once_cell/1.5.2/once_cell/unsync/index.html) has `Lazy` and `OnceCell`,
[Sync](https://docs.rs/once_cell/1.5.2/once_cell/sync/index.html) has `Lazy` and `OnceCell`,
but [Race](https://docs.rs/once_cell/1.5.2/once_cell/race/index.html) has `OnceBox`, `OnceNonZeroUsize` and `OnceBool`. 

`OnceBox` appears to be the same as `OnceCell` in the others but is not named similarly. (It's docs look copied and pasted and make no mention of races).
`Lazy` is missing. I don't know if there is a reason for that. But if not it is useful and would be good to add. 
The other two classes I haven't considered as they don't fit my app's needs.
