### ISSUE TITLE
Add a warning in the FAQ about `const` vs `static`

### ISSUE THREAD

**Issue by jRimbault** [matklad/once_cell#145]
I think some people may have some misconceptions about what `const` and `static` actually means, this came up in [this reddit thread][0] today. I tried explaining shortly by analogy (I'm not the best explainer), the result of the constructor function is copy pasted everywhere the const result is used. Maybe this could warrant a reminder note in the FAQ part of the docs ?

[0]: https://old.reddit.com/r/learnrust/comments/lz1w7b/building_something_inside_a_function/gpznzbb/?context=10000

**Comment by matklad** [comment]
cc https://github.com/rust-lang/rust/issues/40543

**Comment by mrozekma** [comment]
I just made this exact mistake ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1cf5b08cb61e02f4c8b19c42623e0c35)):

```rust
use once_cell::unsync::OnceCell; // 1.9.0

const CELL: OnceCell<bool> = OnceCell::new();

pub fn main() {
    assert_eq!(CELL.set(true), Ok(()));
    assert_eq!(CELL.set(true), Err(true)); // Fails
}
```

I assume based on the linked rust-lang conversation that there's no way for `once_cell` to catch this mistake and it would have to be a compiler change, but a warning in the FAQ might be worthwhile.

**Comment by dsherret** [comment]
I also just hit this. I wonder if perhaps there could be a debug panic if a lazy is initialized twice saying the user likley has it in a `const` by accident.
