### ISSUE TITLE
once_cell::race does not compile on ARM

### ISSUE THREAD

**Issue by tkaitchuck** [matklad/once_cell#155]
These four lines: [1](https://github.com/matklad/once_cell/blob/master/src/race.rs#L41), [2](https://github.com/matklad/once_cell/blob/master/src/race.rs#L82), [3](https://github.com/matklad/once_cell/blob/master/src/race.rs#L214), [4](https://github.com/matklad/once_cell/blob/master/src/race.rs#L260) fail to compile on ARM because on ARM the `AtomicUsize` lacks a `compare_exchange` method.
It may be possible to work around this with a `load` and a `store` and a loop.

**Comment by matklad** [comment]
Do you know which cfg is used to detect if it is available for a particular target?

**Comment by tkaitchuck** [comment]
The only way I am aware of is by using `target_arch = "arm"`. I don't know if there is a list somewhere of which architectures have which features.

**Comment by taiki-e** [comment]
FYI:
- futures, crossbeam, heapless, defmt, etc. handles this issue using the TARGET environment variables provided by cargo for the build script and a list of targets that do not have atomic CAS. See https://github.com/rust-lang/futures-rs/pull/2400 for more.
- Another way that is available in stable rust is to use crates like autocfg. See https://github.com/rust-lang/futures-rs/pull/2294 for more.
