### ISSUE TITLE
parking_lot implementation tests fail under Miri due to compare_exchange_weak failures

### ISSUE THREAD

**Issue by saethlin** [matklad/once_cell#186]
`compare_exchange_weak` is allowed to spuriously fail. By default, Miri makes most calls fail so this panics when running tests: https://github.com/matklad/once_cell/blob/2cdfc1e0a92c8e51534cd91c49f41478a61a5ab6/src/imp_pl.rs#L171

**Comment by RalfJung** [comment]
Looks like this code simply wants `compare_exchange` without the "weak", if it does not want to handle spurious failures?

**Comment by matklad** [comment]
Nah, that’s just a bug, it should have Err(INCOMPLETE) => (), branch

**Comment by matklad** [comment]
@RalfJung in case no-one has told you this yet, miri is very cool, thanks!
