### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by Batarian711** [matklad/once_cell#2]
Hello. I volunteer to help you. I am a graphic designer. I want to design a logo for you to use in the readme file. Do you have an idea? What do you say?

**Comment by matklad** [comment]
Sure, why not! I don't think I have any particular ideas though, I am quite bad at logos, the limit of my abilities is [drop bomb](https://github.com/matklad/drop_bomb) (and that is from https://docs.google.com/presentation/d/1TjWba0CR9RHFm47rvW1nFUlmouaR55Xt235aHyLPf9U/edit actually) :D

**Comment by Batarian711** [comment]
I designed a logo that represents a person. It represents the human cell. Here I have designed a logo that represents similar people and cells. Which one do you prefer? Is there anything you want to add?

![once](https://user-images.githubusercontent.com/41051393/43677675-b8dd5ab0-980e-11e8-99c8-5b46c87b57cd.jpg)

**Comment by matklad** [comment]
Looks perfect!

I like the blue `OnceCell`!

Let's make it an image (probably not jpeg? There should be better formats for graphics I think?), and I'll put it to the readme. Which text/link should I use to refer to use as the author of logo?

**Comment by Batarian711** [comment]
I will send you the necessary files. I will open the pr.

**Comment by Batarian711** [comment]
I sent pr.

**Comment by matklad** [comment]
heh, we've added logo log ago, thanks again @Batarian711 !
