### ISSUE TITLE
`critical_section` based `OnceCell` doesn't need `T: Sync`

### ISSUE THREAD

**Issue by jedel1043** [matklad/once_cell#215]
Correct me if I'm wrong, but `critical-section`'s `Mutex` allows `Mutex<T>` even if `T: !Sync`. However, `OnceCell`'s implementation based on `critical-section` requires `T: Send + Sync`, and syncing is precisely the work of the `Mutex` used. Should this bound be removed?

**Comment by matklad** [comment]
I think it's important that the API is the same regardless of the synchronization primitive used internally.
