### ISSUE TITLE
adding get_unchecked_mut

### ISSUE THREAD

**Issue by bobi6666** [matklad/once_cell#216]
hello is there any steps how you can add get_unchecked_mut()? it can be used for example with rand crate on my side

**Comment by matklad** [comment]
What would be the signature of this method?

**Comment by bobi6666** [comment]
i think fn get_unchecked_mut

2023-01-15 16:32 GMT+01:00, Alex Kladov ***@***.***>:

**Comment by notgull** [comment]
There is already a [`get_mut`](https://docs.rs/once_cell/latest/once_cell/sync/struct.OnceCell.html#method.get_mut) method that I think does what you want

**Comment by bobi6666** [comment]
yes but get_unchecked is lot faster when i using that when i am sure
my cell is initialized and for this reason get_unchecked_mut would be
also faster. normal get is slower when you are not sure if you
initialized or not

2023-01-15 19:28 GMT+01:00, John Nunley ***@***.***>:

**Comment by matklad** [comment]
You can use `get_mut().unwrap_unchecked()`. Though, I would encourage to verify via benchmarks that that’s indeed faster for your use case.
