### ISSUE TITLE
critical-section vs critical_section

### ISSUE THREAD

**Issue by rukai** [matklad/once_cell#217]
Its very easy to accidentally do:
`once_cell = { version = "1.17.0", default-features = false, features = ["critical_section"] }`
instead of:
`once_cell = { version = "1.17.0", default-features = false, features = ["critical-section"] }`

The first one enables the dependency critical_section, which effectively does nothing.
The second enables the dependency critical_section and enables the actual functionality that makes use of the dependency.

We could solve this by implementing the dep as:
`critical_section = ["dep:critical_section", "atomic_polyfill" ]`
but we would have to wait for MSRV to reach 1.60: https://blog.rust-lang.org/2022/04/07/Rust-1.60.0.html#new-syntax-for-cargo-features

**Comment by matklad** [comment]
fixes on master!
