### ISSUE TITLE
`Lazy` returning different results

### ISSUE THREAD

**Issue by kpark-hrp** [matklad/once_cell#224]
For unit testing, I have a const `String` that is randomly generated and shared.
```rust
const CLIENT_ID: Lazy<String> =
        Lazy::new(|| Alphanumeric.sample_string(&mut rand::thread_rng(), 16));
```
---
But it appears that `Lazy` is being evaluated multiple times and returns different `String` each call. I have a very basic equality check unit test to show this.
```rust
#[tokio::test]
async fn test_client_id() {
    assert_eq!(CLIENT_ID.clone(), CLIENT_ID.clone());
}
```

```bash
thread 'tests::test_client_id' panicked at 'assertion failed: `(left == right)`
  left: `"1ScRLmtGM8LcSHNJ"`,
 right: `"DezhUcYvnBbIOtyA"`', oauth/src/bin/authorizer.rs:201:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by kpark-hrp** [comment]
It appears that replacing `const` with `static` fixes the issue.
```rust
static CLIENT_ID: Lazy<String> = Lazy::new(|| Alphanumeric.sample_string(&mut rand::thread_rng(), 16));
```

But, shouldn't `const` still behave the same way where the closure in `Lazy` is only evaluated once and shared?

**Comment by kpark-hrp** [comment]
It appears that this behavior is documented.

> Note that the variable that holds Lazy is declared as static, not const. This is important: using const instead compiles, but works wrong.

But to me, this feels like an unintended behavior which should not compile

**Comment by matklad** [comment]
Yeah, it’s a known language level issue without good solutions, see https://github.com/rust-lang/rust/issues/40543

**Comment by Stargateur** [comment]
`const` is not named right, that more like macro in C, basically it's copy the expression and copy it where you use it. That just a leçon that rust developer learn at some point, nothing is perfect.
