### ISSUE TITLE
Allow unsized types for OnceBox and OnceRef

### ISSUE THREAD

**Issue by neoeinstein** [matklad/once_cell#225]
Because both of these types are held behind a reference, they should be able to accept unsized types, allowing for things like `OnceBox<str>` or `OnceBox<'static, str>`.

**Comment by matklad** [comment]
I am not sure that'll work: we use pointer CAS in the implementation, so we need the pointer to be a narrow one.

**Comment by matklad** [comment]
Yeah, I don't think this could work
