### ISSUE TITLE
Consider writing a guide to migrating to std equivalents

### ISSUE THREAD

**Issue by stackinspector** [matklad/once_cell#258]
This crate is conceptually equivalent to the std features `once_cell` and `lazy_cell`, and any potential inconsistencies in behavior should be highlighted.
Any minor API differences, if there are, should also be listed.

**Comment by matklad** [comment]
Differences with std are already documented to a sufficient degree

**Comment by nyurik** [comment]
I was also looking for these instructions. I do think some minor docs improvements would be helpful.

The starting point could be a short description -- [comparison with std](https://docs.rs/once_cell/latest/once_cell/#comparison-with-std).

Imo, the docs could have a better correspondence table for each type, e.g. [`once_cell::sync::Lazy`](https://docs.rs/once_cell/latest/once_cell/sync/struct.Lazy.html) would match type `std::sync::???`, with differences ...
