### ISSUE TITLE
Feature request: `get_mut_or_init` and `get_mut_or_try_init` in `OnceCell`.

### ISSUE THREAD

**Issue by xuxiaocheng0201** [matklad/once_cell#268]
Since we already have `get`and its corresponding initialization methods `get_or_init` and `get_or_try_init`, why not add `get_mut_or_init` and `get_mut_or_try_init` corresponding to `get_mut`?

These methods are particularly useful during lazy loading. Just like now, I have to use `get_or_try_init` and `get_mut().unwrap()` to simulate `get_mut_or_try_init`. This is not graceful.

**Comment by matklad** [comment]
If you have `&mut` access, you shouldn't use `get_or_try_init` and instead do something like

```
fn f(cell: &mut OnceCell<T>) {
   if cell.get().is_none() {
       *cell = OnceCell::with_value(init()?)
   }
}
```

But chances are, if you have `&mut OnceCell<T>`, you don't actually need `OnceCell` and could use `&mut T` directly?

**Comment by xuxiaocheng0201** [comment]
> But chances are, if you have &mut OnceCell<T>, you don't actually need OnceCell and could use &mut T directly?

I use it in lazy loading. For example, initialize some heavy operations that will be used in a loop that is almost never executed. It seems a bit convoluted, but it shouldn't be a rare situation.

Thank you for your code and quick reply! The code above is indeed what I want!

**Comment by xuxiaocheng0201** [comment]
Okay, in this case, it may be simpler to use `Option` instead of `unsync::OnceCell`.
```rust
fn get_mut_or_try_init<T, F: FnOnce() -> Result<T, E>, E>(cell: &mut Option<T>, init: F) -> Result<&mut T, E> {
    if cell.is_none() {
        *cell = Some(init()?)
    }
    Ok(cell.as_mut().unwrap())
}
```

**Comment by matklad** [comment]
Yup, there is https://doc.rust-lang.org/stable/std/option/enum.Option.html#method.get_or_insert_with


There's no `try` version in std though
