### ISSUE TITLE
Feature request: Add OnceCell::try_unwrap()

### ISSUE THREAD

**Issue by manuthambi** [matklad/once_cell#28]
Add a method which consumes OnceCell and returns the element if it exists.
The method signature can be very similar to Arc::try_unwrap().

`pub fn try_unwrap(self) -> Result<T, OnceCell<T>>`

**Comment by manuthambi** [comment]
On second thought, there isn't much point in returning an uninitialized OnceCell if the unwrap fails.
So the signature could be:
`pub fn try_unwrap(self) -> Option<T>`

**Comment by matklad** [comment]
sgmt, though, I think the name and signature should be, to map `RefCell`:

```
pub fn into_inner(self) -> Option<T>
```

**Comment by manuthambi** [comment]
`into_inner` sounds better, and it is better to be consistent with `RefCell`.

I haven't contributed to Rust before, but do you want me to send you a pull request?

**Comment by matklad** [comment]
Sure, that would be awesome! Here's a checklist of things to do:

- [ ] add the method to the `unsync` variant
- [ ] add the method to both versions of the `sync` variant
- [ ] write a short docstring for them, with a doc test
- [ ] write a simple smoke test
