### ISSUE TITLE
Feature request: impl Clone

### ISSUE THREAD

**Issue by starkat99** [matklad/once_cell#4]
impl Clone for OnceCell<T> where T: Clone

Finding myself in need of Cloning. I'm guessing Lazy can't be, but OnceCell would be helpful?

**Comment by matklad** [comment]
unsync::OnceCell is now Clone

**Comment by mmstick** [comment]
Would it be reasonable to support this for `sync::OnceCell` as well?

**Comment by mmstick** [comment]
I guess `Arc<OnceCell>` achieves this.
