### ISSUE TITLE
Document impact of enabling parking_lot

### ISSUE THREAD

**Issue by najamelan** [matklad/once_cell#40]
It's obvious that this will add more dependencies, but what is the advantage? 

If it's for performance, are there any benchmarks showing the difference?

**Comment by matklad** [comment]
Good call!

At the moment:

* there’s no perf difference for hot path 
* using parking lot makes sizes of struct a smaller
* (until https://github.com/matklad/once_cell/pull/39 is released) it enables get_or_try_init

**Comment by najamelan** [comment]
Ok thanks a lot for clarifying. I will stick to the std version then, because the keeping the dependency tree small is more important for me.

**Comment by matklad** [comment]
The recent release includes both #39 and some docs about parking lot effects!
