### ISSUE TITLE
A way to check if a OnceCell is initialized?

### ISSUE THREAD

**Issue by konsumlamm** [matklad/once_cell#96]
As far as i can tell, there is currently no `is_initialized` function for the `OnceCell`s (and transitively the `Lazy` types). It could trivially be implemented like this (for `OnceCell`):
```rust
pub fn is_initialized(&self) -> bool {
    self.get().is_some()
}
```
Is there any reason this doesn't exist yet? If not, I could make a PR for it.

**Comment by matklad** [comment]
There's no "active" reason for this function not existing, but I think `self.get().is_some()` would probably be more clear anyway.

**Comment by konsumlamm** [comment]
> I think `self.get().is_some()` would probably be more clear anyway

How so? I think `self.is_initialized()` clarifies the intent better.
Btw, is there a reason `get`, `get_mut` and `into_inner` aren't exposed by `Lazy`?

**Comment by matklad** [comment]
Closing: I don't think this pulls its weight (and Lazy::get now exists)
